[package]
name = "pbr"
version = "0.1.0"
edition = "2021"

[dependencies]
glam = { version = "0.21.2", features = ["glam-assert", "bytemuck"] }
bytemuck = { version = "1.9.1", features = ["derive"] }
eyre = "0.6.7"
gl = "0.14.0"
gltf = "1.0.0"
egui_sdl2_gl = "0.16.0"
egui = "0.16"
sdl2 = "0.35"
image = { version = "0.24.2", features = ["png", "jpeg", "hdr"] }

[profile.dev.package."*"]
opt-level = 3
